version: '3'

dotenv: ['.env']

vars:
  MAIN: compose.yml
  LOAD: load-compose.yml

tasks:


  load:
    desc: "Load CSVs into source DB (run once)"
    cmds:
      - docker compose -f {{.LOAD}} up --build --remove-orphans
      - docker compose -f {{.LOAD}} down --remove-orphans


  up:
    desc: "Start all services"
    cmds:
      - docker compose -f {{.MAIN}} up -d --remove-orphans

  down:
    desc: "Stop all services"
    cmds:
      - docker compose -f {{.MAIN}} down --remove-orphans

  restart:
    desc: "Restart all services"
    cmds:
      - task: down
      - task: up

  build:
    desc: "Rebuild images"
    cmds:
      - docker compose -f {{.MAIN}} build


  logs:
    desc: "All logs"
    cmds:
      - docker compose -f {{.MAIN}} logs -f

  logs-spark:
    desc: "Spark streaming logs"
    cmds:
      - docker compose -f {{.MAIN}} logs -f streaming-app

  logs-kafka:
    desc: "Kafka logs"
    cmds:
      - docker compose -f {{.MAIN}} logs -f kafka

  logs-debezium:
    desc: "Debezium connector logs"
    cmds:
      - docker compose -f {{.MAIN}} logs -f kafka-connect


  status:
    desc: "Container status"
    cmds:
      - docker compose -f {{.MAIN}} ps

  connector:
    desc: "Check Debezium connector status"
    cmds:
      - curl -s http://localhost:8083/connectors/postgres-connector/status | python -m json.tool


  db-source:
    desc: "Connect to source DB (niwa)"
    cmds:
      - psql -h localhost -U {{.DB_USER}} -d niwa

  db-silver:
    desc: "Connect to silver DB (ecommerce_db)"
    cmds:
      - psql -h localhost -U {{.DB_USER}} -d {{.DB_NAME}}

  refresh-gold:
    desc: "Manually refresh all gold materialized views"
    cmds:
      - psql -h localhost -U {{.DB_USER}} -d {{.DB_NAME}} -c "
          REFRESH MATERIALIZED VIEW gold_sales_monthly;
          REFRESH MATERIALIZED VIEW gold_sales_daily;
          REFRESH MATERIALIZED VIEW gold_customer_metrics;
          REFRESH MATERIALIZED VIEW gold_product_performance;
          REFRESH MATERIALIZED VIEW gold_seller_performance;
          REFRESH MATERIALIZED VIEW gold_delivery_analytics;
          REFRESH MATERIALIZED VIEW gold_payment_analytics;
        "

  clean:
    desc: "Stop and remove all volumes"
    prompt: "This will delete all Kafka, Zookeeper and Spark data. Continue?"
    cmds:
      - docker compose -f {{.MAIN}} down -v --remove-orphans

  clean-checkpoints:
    desc: "Clear Spark checkpoints (restream from scratch)"
    prompt: "Duplicate data may occur. Continue?"
    cmds:
      - rm -rf ./checkpoints/*